/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const LiveReactionType = IDL.Variant({
  'heart' : IDL.Null,
  'clap' : IDL.Null,
  'fire' : IDL.Null,
  'wave' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateGroupArgs = IDL.Record({
  'creator' : IDL.Principal,
  'adminIds' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
});
export const MediaContent = IDL.Record({
  'video' : IDL.Opt(ExternalBlob),
  'text' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(ExternalBlob),
});
export const PostType = IDL.Variant({
  'regular' : IDL.Null,
  'newsFeed' : IDL.Null,
});
export const LiveSessionStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'live' : IDL.Null,
  'ended' : IDL.Null,
});
export const LiveSession = IDL.Record({
  'id' : IDL.Nat,
  'status' : LiveSessionStatus,
  'title' : IDL.Text,
  'startedAt' : IDL.Opt(IDL.Int),
  'topic' : IDL.Text,
  'endedAt' : IDL.Opt(IDL.Int),
  'scheduledTime' : IDL.Int,
  'leader' : IDL.Principal,
  'constituency' : IDL.Text,
  'viewerCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'badges' : IDL.Vec(IDL.Text),
  'civicTokenBalance' : IDL.Nat,
  'verifiedStatus' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'location' : IDL.Text,
});
export const Group = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
});
export const Page = IDL.Record({
  'owner' : IDL.Principal,
  'profileImage' : IDL.Opt(ExternalBlob),
  'pageName' : IDL.Text,
  'description' : IDL.Text,
  'creationTime' : Time,
  'isPrivate' : IDL.Bool,
  'category' : IDL.Text,
});
export const Poll = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'question' : IDL.Text,
  'votes' : IDL.Vec(IDL.Nat),
  'isPublic' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const PostEdit = IDL.Record({
  'content' : MediaContent,
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'seriousLikeCount' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'content' : MediaContent,
  'author' : IDL.Principal,
  'groupId' : IDL.Opt(IDL.Nat),
  'isEdited' : IDL.Bool,
  'editHistory' : IDL.Vec(PostEdit),
  'timestamp' : Time,
});
export const LiveComment = IDL.Record({
  'id' : IDL.Nat,
  'isModerated' : IDL.Bool,
  'upvotes' : IDL.Vec(IDL.Principal),
  'content' : IDL.Text,
  'parentCommentId' : IDL.Opt(IDL.Nat),
  'authorId' : IDL.Principal,
  'moderationReason' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Nat,
});
export const LiveReaction = IDL.Record({
  'authorId' : IDL.Principal,
  'reactionType' : LiveReactionType,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLiveComment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'addLiveReaction' : IDL.Func([IDL.Nat, LiveReactionType], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([CreateGroupArgs], [IDL.Nat], []),
  'createLiveSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'createPage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPoll' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func(
      [MediaContent, IDL.Opt(IDL.Nat), PostType],
      [IDL.Nat],
      [],
    ),
  'endLiveSession' : IDL.Func([IDL.Nat], [], []),
  'getActiveSessions' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
  'getAllLiveSessions' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
  'getLeaderArchive' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
  'getLiveSession' : IDL.Func([IDL.Nat], [IDL.Opt(LiveSession)], ['query']),
  'getPage' : IDL.Func([IDL.Nat], [IDL.Opt(Page)], ['query']),
  'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(Poll)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getScheduledSessions' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
  'getSessionComments' : IDL.Func([IDL.Nat], [IDL.Vec(LiveComment)], ['query']),
  'getSessionReactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LiveReaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementSessionViewers' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'moderateLiveComment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startLiveSession' : IDL.Func([IDL.Nat], [], []),
  'upvoteQuestion' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const LiveReactionType = IDL.Variant({
    'heart' : IDL.Null,
    'clap' : IDL.Null,
    'fire' : IDL.Null,
    'wave' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateGroupArgs = IDL.Record({
    'creator' : IDL.Principal,
    'adminIds' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
  });
  const MediaContent = IDL.Record({
    'video' : IDL.Opt(ExternalBlob),
    'text' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(ExternalBlob),
  });
  const PostType = IDL.Variant({ 'regular' : IDL.Null, 'newsFeed' : IDL.Null });
  const LiveSessionStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'live' : IDL.Null,
    'ended' : IDL.Null,
  });
  const LiveSession = IDL.Record({
    'id' : IDL.Nat,
    'status' : LiveSessionStatus,
    'title' : IDL.Text,
    'startedAt' : IDL.Opt(IDL.Int),
    'topic' : IDL.Text,
    'endedAt' : IDL.Opt(IDL.Int),
    'scheduledTime' : IDL.Int,
    'leader' : IDL.Principal,
    'constituency' : IDL.Text,
    'viewerCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'badges' : IDL.Vec(IDL.Text),
    'civicTokenBalance' : IDL.Nat,
    'verifiedStatus' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Group = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
  });
  const Page = IDL.Record({
    'owner' : IDL.Principal,
    'profileImage' : IDL.Opt(ExternalBlob),
    'pageName' : IDL.Text,
    'description' : IDL.Text,
    'creationTime' : Time,
    'isPrivate' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Poll = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'question' : IDL.Text,
    'votes' : IDL.Vec(IDL.Nat),
    'isPublic' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const PostEdit = IDL.Record({ 'content' : MediaContent, 'timestamp' : Time });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'seriousLikeCount' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'content' : MediaContent,
    'author' : IDL.Principal,
    'groupId' : IDL.Opt(IDL.Nat),
    'isEdited' : IDL.Bool,
    'editHistory' : IDL.Vec(PostEdit),
    'timestamp' : Time,
  });
  const LiveComment = IDL.Record({
    'id' : IDL.Nat,
    'isModerated' : IDL.Bool,
    'upvotes' : IDL.Vec(IDL.Principal),
    'content' : IDL.Text,
    'parentCommentId' : IDL.Opt(IDL.Nat),
    'authorId' : IDL.Principal,
    'moderationReason' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Nat,
  });
  const LiveReaction = IDL.Record({
    'authorId' : IDL.Principal,
    'reactionType' : LiveReactionType,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLiveComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'addLiveReaction' : IDL.Func([IDL.Nat, LiveReactionType], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([CreateGroupArgs], [IDL.Nat], []),
    'createLiveSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'createPage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createPoll' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func(
        [MediaContent, IDL.Opt(IDL.Nat), PostType],
        [IDL.Nat],
        [],
      ),
    'endLiveSession' : IDL.Func([IDL.Nat], [], []),
    'getActiveSessions' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
    'getAllLiveSessions' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
    'getLeaderArchive' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
    'getLiveSession' : IDL.Func([IDL.Nat], [IDL.Opt(LiveSession)], ['query']),
    'getPage' : IDL.Func([IDL.Nat], [IDL.Opt(Page)], ['query']),
    'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(Poll)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getScheduledSessions' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
    'getSessionComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LiveComment)],
        ['query'],
      ),
    'getSessionReactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LiveReaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementSessionViewers' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'moderateLiveComment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startLiveSession' : IDL.Func([IDL.Nat], [], []),
    'upvoteQuestion' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };