/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateGroupArgs {
  'creator' : Principal,
  'adminIds' : Array<Principal>,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'coverImage' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface Group {
  'id' : bigint,
  'creator' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'coverImage' : [] | [ExternalBlob],
}
export interface LiveComment {
  'id' : bigint,
  'isModerated' : boolean,
  'upvotes' : Array<Principal>,
  'content' : string,
  'parentCommentId' : [] | [bigint],
  'authorId' : Principal,
  'moderationReason' : [] | [string],
  'timestamp' : bigint,
  'sessionId' : bigint,
}
export interface LiveReaction {
  'authorId' : Principal,
  'reactionType' : LiveReactionType,
  'timestamp' : bigint,
  'sessionId' : bigint,
}
export type LiveReactionType = { 'heart' : null } |
  { 'clap' : null } |
  { 'fire' : null } |
  { 'wave' : null };
export interface LiveSession {
  'id' : bigint,
  'status' : LiveSessionStatus,
  'title' : string,
  'startedAt' : [] | [bigint],
  'topic' : string,
  'endedAt' : [] | [bigint],
  'scheduledTime' : bigint,
  'leader' : Principal,
  'constituency' : string,
  'viewerCount' : bigint,
}
export type LiveSessionStatus = { 'scheduled' : null } |
  { 'live' : null } |
  { 'ended' : null };
export interface MediaContent {
  'video' : [] | [ExternalBlob],
  'text' : [] | [string],
  'image' : [] | [ExternalBlob],
}
export interface Page {
  'owner' : Principal,
  'profileImage' : [] | [ExternalBlob],
  'pageName' : string,
  'description' : string,
  'creationTime' : Time,
  'isPrivate' : boolean,
  'category' : string,
}
export interface Poll {
  'id' : bigint,
  'creator' : Principal,
  'question' : string,
  'votes' : Array<bigint>,
  'isPublic' : boolean,
  'options' : Array<string>,
}
export interface Post {
  'id' : bigint,
  'postType' : PostType,
  'seriousLikeCount' : bigint,
  'likeCount' : bigint,
  'content' : MediaContent,
  'author' : Principal,
  'groupId' : [] | [bigint],
  'isEdited' : boolean,
  'editHistory' : Array<PostEdit>,
  'timestamp' : Time,
}
export interface PostEdit { 'content' : MediaContent, 'timestamp' : Time }
export type PostType = { 'regular' : null } |
  { 'newsFeed' : null };
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'badges' : Array<string>,
  'civicTokenBalance' : bigint,
  'verifiedStatus' : boolean,
  'followerCount' : bigint,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLiveComment' : ActorMethod<[bigint, string, [] | [bigint]], bigint>,
  'addLiveReaction' : ActorMethod<[bigint, LiveReactionType], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[CreateGroupArgs], bigint>,
  'createLiveSession' : ActorMethod<[string, string, string, bigint], bigint>,
  'createPage' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], boolean],
    bigint
  >,
  'createPoll' : ActorMethod<[string, Array<string>, boolean], bigint>,
  'createPost' : ActorMethod<[MediaContent, [] | [bigint], PostType], bigint>,
  'endLiveSession' : ActorMethod<[bigint], undefined>,
  'getActiveSessions' : ActorMethod<[], Array<LiveSession>>,
  'getAllLiveSessions' : ActorMethod<[], Array<LiveSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroup' : ActorMethod<[bigint], [] | [Group]>,
  'getLeaderArchive' : ActorMethod<[], Array<LiveSession>>,
  'getLiveSession' : ActorMethod<[bigint], [] | [LiveSession]>,
  'getPage' : ActorMethod<[bigint], [] | [Page]>,
  'getPoll' : ActorMethod<[bigint], [] | [Poll]>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getScheduledSessions' : ActorMethod<[], Array<LiveSession>>,
  'getSessionComments' : ActorMethod<[bigint], Array<LiveComment>>,
  'getSessionReactions' : ActorMethod<[bigint], Array<LiveReaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementSessionViewers' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moderateLiveComment' : ActorMethod<[bigint, bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startLiveSession' : ActorMethod<[bigint], undefined>,
  'upvoteQuestion' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];