/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaContent = IDL.Record({
  'video' : IDL.Opt(ExternalBlob),
  'text' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const Page = IDL.Record({
  'owner' : IDL.Principal,
  'profileImage' : IDL.Opt(ExternalBlob),
  'pageName' : IDL.Text,
  'description' : IDL.Text,
  'creationTime' : Time,
  'isPrivate' : IDL.Bool,
  'category' : IDL.Text,
});
export const PointHistory = IDL.Record({
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'date' : IDL.Int,
  'actionType' : IDL.Text,
  'points' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'badges' : IDL.Vec(IDL.Text),
  'civicTokenBalance' : IDL.Nat,
  'verifiedStatus' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'location' : IDL.Text,
});
export const Wallet = IDL.Record({
  'lastLoginDate' : IDL.Int,
  'dailyEarned' : IDL.Float64,
  'totalEarned' : IDL.Float64,
  'civPoints' : IDL.Float64,
  'level' : IDL.Float64,
  'lastResetDate' : IDL.Int,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'parentCommentId' : IDL.Opt(IDL.Nat),
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'likes' : IDL.Vec(IDL.Principal),
  'updatedAt' : IDL.Opt(IDL.Int),
  'postId' : IDL.Text,
});
export const Group = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
});
export const GroupMembership = IDL.Record({
  'joinedAt' : Time,
  'user' : IDL.Principal,
  'groupId' : IDL.Nat,
});
export const Poll = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'question' : IDL.Text,
  'votes' : IDL.Vec(IDL.Nat),
  'isPublic' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const PostType = IDL.Variant({
  'regular' : IDL.Null,
  'newsFeed' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'seriousLikeCount' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'content' : MediaContent,
  'author' : IDL.Principal,
  'groupId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'createNewsFeedPost' : IDL.Func([MediaContent], [IDL.Nat], []),
  'createPage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPoll' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func([MediaContent, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteGroup' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'editComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllPages' : IDL.Func([], [IDL.Vec(Page)], ['query']),
  'getCallerPointHistory' : IDL.Func([], [IDL.Vec(PointHistory)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'getCommentLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getCommentsByPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getCountries' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDistrictsByState' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
  'getGroupMembers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(GroupMembership)],
      ['query'],
    ),
  'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getPointHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PointHistory)],
      ['query'],
    ),
  'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(Poll)], ['query']),
  'getPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getStatesByCountry' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserPages' : IDL.Func([IDL.Principal], [IDL.Vec(Page)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([IDL.Principal], [IDL.Opt(Wallet)], ['query']),
  'hasLikedPost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'hasVotedOnPoll' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Nat], [], []),
  'leaveGroup' : IDL.Func([IDL.Nat], [], []),
  'likeComment' : IDL.Func([IDL.Nat], [], []),
  'likePost' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'votePoll' : IDL.Func([IDL.Nat, IDL.Nat], [Poll], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaContent = IDL.Record({
    'video' : IDL.Opt(ExternalBlob),
    'text' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const Page = IDL.Record({
    'owner' : IDL.Principal,
    'profileImage' : IDL.Opt(ExternalBlob),
    'pageName' : IDL.Text,
    'description' : IDL.Text,
    'creationTime' : Time,
    'isPrivate' : IDL.Bool,
    'category' : IDL.Text,
  });
  const PointHistory = IDL.Record({
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'date' : IDL.Int,
    'actionType' : IDL.Text,
    'points' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'badges' : IDL.Vec(IDL.Text),
    'civicTokenBalance' : IDL.Nat,
    'verifiedStatus' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Wallet = IDL.Record({
    'lastLoginDate' : IDL.Int,
    'dailyEarned' : IDL.Float64,
    'totalEarned' : IDL.Float64,
    'civPoints' : IDL.Float64,
    'level' : IDL.Float64,
    'lastResetDate' : IDL.Int,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'parentCommentId' : IDL.Opt(IDL.Nat),
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'likes' : IDL.Vec(IDL.Principal),
    'updatedAt' : IDL.Opt(IDL.Int),
    'postId' : IDL.Text,
  });
  const Group = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
  });
  const GroupMembership = IDL.Record({
    'joinedAt' : Time,
    'user' : IDL.Principal,
    'groupId' : IDL.Nat,
  });
  const Poll = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'question' : IDL.Text,
    'votes' : IDL.Vec(IDL.Nat),
    'isPublic' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const PostType = IDL.Variant({ 'regular' : IDL.Null, 'newsFeed' : IDL.Null });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'seriousLikeCount' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'content' : MediaContent,
    'author' : IDL.Principal,
    'groupId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'createNewsFeedPost' : IDL.Func([MediaContent], [IDL.Nat], []),
    'createPage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createPoll' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func([MediaContent, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteGroup' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'editComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllPages' : IDL.Func([], [IDL.Vec(Page)], ['query']),
    'getCallerPointHistory' : IDL.Func([], [IDL.Vec(PointHistory)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'getCommentLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getCommentsByPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getCountries' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDistrictsByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
    'getGroupMembers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GroupMembership)],
        ['query'],
      ),
    'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getPointHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PointHistory)],
        ['query'],
      ),
    'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(Poll)], ['query']),
    'getPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getStatesByCountry' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserPages' : IDL.Func([IDL.Principal], [IDL.Vec(Page)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([IDL.Principal], [IDL.Opt(Wallet)], ['query']),
    'hasLikedPost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'hasVotedOnPoll' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Nat], [], []),
    'leaveGroup' : IDL.Func([IDL.Nat], [], []),
    'likeComment' : IDL.Func([IDL.Nat], [], []),
    'likePost' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'votePoll' : IDL.Func([IDL.Nat, IDL.Nat], [Poll], []),
  });
};

export const init = ({ IDL }) => { return []; };