/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'parentCommentId' : [] | [bigint],
  'authorId' : Principal,
  'createdAt' : bigint,
  'likes' : Array<Principal>,
  'updatedAt' : [] | [bigint],
  'postId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Group {
  'id' : bigint,
  'creator' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'coverImage' : [] | [ExternalBlob],
}
export interface GroupMembership {
  'joinedAt' : Time,
  'user' : Principal,
  'groupId' : bigint,
}
export interface MediaContent {
  'video' : [] | [ExternalBlob],
  'text' : [] | [string],
  'image' : [] | [ExternalBlob],
}
export interface Page {
  'owner' : Principal,
  'profileImage' : [] | [ExternalBlob],
  'pageName' : string,
  'description' : string,
  'creationTime' : Time,
  'isPrivate' : boolean,
  'category' : string,
}
export interface PointHistory {
  'status' : string,
  'userId' : Principal,
  'date' : bigint,
  'actionType' : string,
  'points' : number,
}
export interface Poll {
  'id' : bigint,
  'creator' : Principal,
  'question' : string,
  'votes' : Array<bigint>,
  'isPublic' : boolean,
  'options' : Array<string>,
}
export interface Post {
  'id' : bigint,
  'postType' : PostType,
  'seriousLikeCount' : bigint,
  'likeCount' : bigint,
  'content' : MediaContent,
  'author' : Principal,
  'groupId' : [] | [bigint],
  'timestamp' : Time,
}
export type PostType = { 'regular' : null } |
  { 'newsFeed' : null };
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'badges' : Array<string>,
  'civicTokenBalance' : bigint,
  'verifiedStatus' : boolean,
  'followerCount' : bigint,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'lastLoginDate' : bigint,
  'dailyEarned' : number,
  'totalEarned' : number,
  'civPoints' : number,
  'level' : number,
  'lastResetDate' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string, [] | [bigint]], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string, string, [] | [ExternalBlob]], bigint>,
  'createNewsFeedPost' : ActorMethod<[MediaContent], bigint>,
  'createPage' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], boolean],
    bigint
  >,
  'createPoll' : ActorMethod<[string, Array<string>, boolean], bigint>,
  'createPost' : ActorMethod<[MediaContent, [] | [bigint]], bigint>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteGroup' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'editComment' : ActorMethod<[bigint, string], undefined>,
  'getAllPages' : ActorMethod<[], Array<Page>>,
  'getCallerPointHistory' : ActorMethod<[], Array<PointHistory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWallet' : ActorMethod<[], [] | [Wallet]>,
  'getCommentLikeCount' : ActorMethod<[bigint], bigint>,
  'getCommentsByPost' : ActorMethod<[string], Array<Comment>>,
  'getCountries' : ActorMethod<[], Array<string>>,
  'getDistrictsByState' : ActorMethod<[string], Array<string>>,
  'getGroup' : ActorMethod<[bigint], [] | [Group]>,
  'getGroupMembers' : ActorMethod<[bigint], Array<GroupMembership>>,
  'getGroups' : ActorMethod<[], Array<Group>>,
  'getPointHistory' : ActorMethod<[Principal], Array<PointHistory>>,
  'getPoll' : ActorMethod<[bigint], [] | [Poll]>,
  'getPolls' : ActorMethod<[], Array<Poll>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getStatesByCountry' : ActorMethod<[string], Array<string>>,
  'getUserPages' : ActorMethod<[Principal], Array<Page>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[Principal], [] | [Wallet]>,
  'hasLikedPost' : ActorMethod<[bigint], boolean>,
  'hasVotedOnPoll' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[bigint], undefined>,
  'leaveGroup' : ActorMethod<[bigint], undefined>,
  'likeComment' : ActorMethod<[bigint], undefined>,
  'likePost' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unlikePost' : ActorMethod<[bigint], bigint>,
  'votePoll' : ActorMethod<[bigint, bigint], Poll>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];