/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface LiveReaction {
    authorId: Principal;
    reactionType: LiveReactionType;
    timestamp: bigint;
    sessionId: bigint;
}
export interface CreateGroupArgs {
    creator: Principal;
    adminIds: Array<Principal>;
    name: string;
    createdAt: Time;
    description: string;
    coverImage?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Group {
    id: bigint;
    creator: Principal;
    name: string;
    createdAt: Time;
    description: string;
    coverImage?: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Poll {
    id: bigint;
    creator: Principal;
    question: string;
    votes: Array<bigint>;
    isPublic: boolean;
    options: Array<string>;
}
export interface Page {
    owner: Principal;
    profileImage?: ExternalBlob;
    pageName: string;
    description: string;
    creationTime: Time;
    isPrivate: boolean;
    category: string;
}
export interface Post {
    id: bigint;
    postType: PostType;
    seriousLikeCount: bigint;
    likeCount: bigint;
    content: MediaContent;
    author: Principal;
    groupId?: bigint;
    isEdited: boolean;
    editHistory: Array<PostEdit>;
    timestamp: Time;
}
export interface LiveComment {
    id: bigint;
    isModerated: boolean;
    upvotes: Array<Principal>;
    content: string;
    parentCommentId?: bigint;
    authorId: Principal;
    moderationReason?: string;
    timestamp: bigint;
    sessionId: bigint;
}
export interface MediaContent {
    video?: ExternalBlob;
    text?: string;
    image?: ExternalBlob;
}
export interface LiveSession {
    id: bigint;
    status: LiveSessionStatus;
    title: string;
    startedAt?: bigint;
    topic: string;
    endedAt?: bigint;
    scheduledTime: bigint;
    leader: Principal;
    constituency: string;
    viewerCount: bigint;
}
export interface PostEdit {
    content: MediaContent;
    timestamp: Time;
}
export interface UserProfile {
    bio: string;
    name: string;
    profilePhoto?: ExternalBlob;
    badges: Array<string>;
    civicTokenBalance: bigint;
    verifiedStatus: boolean;
    followerCount: bigint;
    location: string;
}
export enum LiveReactionType {
    heart = "heart",
    clap = "clap",
    fire = "fire",
    wave = "wave"
}
export enum LiveSessionStatus {
    scheduled = "scheduled",
    live = "live",
    ended = "ended"
}
export enum PostType {
    regular = "regular",
    newsFeed = "newsFeed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLiveComment(sessionId: bigint, content: string, parentCommentId: bigint | null): Promise<bigint>;
    addLiveReaction(sessionId: bigint, reactionType: LiveReactionType): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGroup(args: CreateGroupArgs): Promise<bigint>;
    createLiveSession(title: string, topic: string, constituency: string, scheduledTime: bigint): Promise<bigint>;
    createPage(pageName: string, category: string, description: string, profileImage: ExternalBlob | null, isPrivate: boolean): Promise<bigint>;
    createPoll(question: string, options: Array<string>, isPublic: boolean): Promise<bigint>;
    createPost(content: MediaContent, groupId: bigint | null, postType: PostType): Promise<bigint>;
    endLiveSession(sessionId: bigint): Promise<void>;
    getActiveSessions(): Promise<Array<LiveSession>>;
    getAllLiveSessions(): Promise<Array<LiveSession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGroup(groupId: bigint): Promise<Group | null>;
    getLeaderArchive(): Promise<Array<LiveSession>>;
    getLiveSession(sessionId: bigint): Promise<LiveSession | null>;
    getPage(pageId: bigint): Promise<Page | null>;
    getPoll(pollId: bigint): Promise<Poll | null>;
    getPost(postId: bigint): Promise<Post | null>;
    getScheduledSessions(): Promise<Array<LiveSession>>;
    getSessionComments(sessionId: bigint): Promise<Array<LiveComment>>;
    getSessionReactions(sessionId: bigint): Promise<Array<LiveReaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementSessionViewers(sessionId: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    moderateLiveComment(sessionId: bigint, commentId: bigint, reason: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startLiveSession(sessionId: bigint): Promise<void>;
    upvoteQuestion(sessionId: bigint, commentId: bigint): Promise<void>;
}
import type { CreateGroupArgs as _CreateGroupArgs, ExternalBlob as _ExternalBlob, Group as _Group, LiveComment as _LiveComment, LiveReaction as _LiveReaction, LiveReactionType as _LiveReactionType, LiveSession as _LiveSession, LiveSessionStatus as _LiveSessionStatus, MediaContent as _MediaContent, Page as _Page, Poll as _Poll, Post as _Post, PostEdit as _PostEdit, PostType as _PostType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLiveComment(arg0: bigint, arg1: string, arg2: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLiveComment(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLiveComment(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addLiveReaction(arg0: bigint, arg1: LiveReactionType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLiveReaction(arg0, to_candid_LiveReactionType_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLiveReaction(arg0, to_candid_LiveReactionType_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGroup(arg0: CreateGroupArgs): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(await to_candid_CreateGroupArgs_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(await to_candid_CreateGroupArgs_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createLiveSession(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLiveSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLiveSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createPage(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPage(arg0, arg1, arg2, await to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPage(arg0, arg1, arg2, await to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createPoll(arg0: string, arg1: Array<string>, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0, arg1, arg2);
            return result;
        }
    }
    async createPost(arg0: MediaContent, arg1: bigint | null, arg2: PostType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(await to_candid_MediaContent_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_PostType_n19(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(await to_candid_MediaContent_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_PostType_n19(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async endLiveSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endLiveSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endLiveSession(arg0);
            return result;
        }
    }
    async getActiveSessions(): Promise<Array<LiveSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSessions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSessions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLiveSessions(): Promise<Array<LiveSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLiveSessions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLiveSessions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroup(arg0: bigint): Promise<Group | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroup(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroup(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderArchive(): Promise<Array<LiveSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderArchive();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderArchive();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveSession(arg0: bigint): Promise<LiveSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveSession(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveSession(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPage(arg0: bigint): Promise<Page | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPage(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPage(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoll(arg0: bigint): Promise<Poll | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoll(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoll(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScheduledSessions(): Promise<Array<LiveSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduledSessions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduledSessions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionComments(arg0: bigint): Promise<Array<LiveComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionComments(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionComments(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionReactions(arg0: bigint): Promise<Array<LiveReaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionReactions(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionReactions(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementSessionViewers(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementSessionViewers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementSessionViewers(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async moderateLiveComment(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moderateLiveComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moderateLiveComment(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startLiveSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startLiveSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startLiveSession(arg0);
            return result;
        }
    }
    async upvoteQuestion(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteQuestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteQuestion(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Group_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Group): Promise<Group> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_LiveComment_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveComment): LiveComment {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_LiveReactionType_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveReactionType): LiveReactionType {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_LiveReaction_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveReaction): LiveReaction {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_LiveSessionStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveSessionStatus): LiveSessionStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_LiveSession_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveSession): LiveSession {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_MediaContent_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaContent): Promise<MediaContent> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_Page_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Promise<Page> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_PostEdit_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostEdit): Promise<PostEdit> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_PostType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostType): PostType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Group]): Promise<Group | null> {
    return value.length === 0 ? null : await from_candid_Group_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LiveSession]): LiveSession | null {
    return value.length === 0 ? null : from_candid_LiveSession_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Page]): Promise<Page | null> {
    return value.length === 0 ? null : await from_candid_Page_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Poll]): Poll | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Promise<Post | null> {
    return value.length === 0 ? null : await from_candid_Post_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LiveSessionStatus;
    title: string;
    startedAt: [] | [bigint];
    topic: string;
    endedAt: [] | [bigint];
    scheduledTime: bigint;
    leader: Principal;
    constituency: string;
    viewerCount: bigint;
}): {
    id: bigint;
    status: LiveSessionStatus;
    title: string;
    startedAt?: bigint;
    topic: string;
    endedAt?: bigint;
    scheduledTime: bigint;
    leader: Principal;
    constituency: string;
    viewerCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_LiveSessionStatus_n24(_uploadFile, _downloadFile, value.status),
        title: value.title,
        startedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.startedAt)),
        topic: value.topic,
        endedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.endedAt)),
        scheduledTime: value.scheduledTime,
        leader: value.leader,
        constituency: value.constituency,
        viewerCount: value.viewerCount
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    badges: Array<string>;
    civicTokenBalance: bigint;
    verifiedStatus: boolean;
    followerCount: bigint;
    location: string;
}): Promise<{
    bio: string;
    name: string;
    profilePhoto?: ExternalBlob;
    badges: Array<string>;
    civicTokenBalance: bigint;
    verifiedStatus: boolean;
    followerCount: bigint;
    location: string;
}> {
    return {
        bio: value.bio,
        name: value.name,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.profilePhoto)),
        badges: value.badges,
        civicTokenBalance: value.civicTokenBalance,
        verifiedStatus: value.verifiedStatus,
        followerCount: value.followerCount,
        location: value.location
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    creator: Principal;
    name: string;
    createdAt: _Time;
    description: string;
    coverImage: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    creator: Principal;
    name: string;
    createdAt: Time;
    description: string;
    coverImage?: ExternalBlob;
}> {
    return {
        id: value.id,
        creator: value.creator,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        coverImage: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.coverImage))
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    profileImage: [] | [_ExternalBlob];
    pageName: string;
    description: string;
    creationTime: _Time;
    isPrivate: boolean;
    category: string;
}): Promise<{
    owner: Principal;
    profileImage?: ExternalBlob;
    pageName: string;
    description: string;
    creationTime: Time;
    isPrivate: boolean;
    category: string;
}> {
    return {
        owner: value.owner,
        profileImage: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.profileImage)),
        pageName: value.pageName,
        description: value.description,
        creationTime: value.creationTime,
        isPrivate: value.isPrivate,
        category: value.category
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    postType: _PostType;
    seriousLikeCount: bigint;
    likeCount: bigint;
    content: _MediaContent;
    author: Principal;
    groupId: [] | [bigint];
    isEdited: boolean;
    editHistory: Array<_PostEdit>;
    timestamp: _Time;
}): Promise<{
    id: bigint;
    postType: PostType;
    seriousLikeCount: bigint;
    likeCount: bigint;
    content: MediaContent;
    author: Principal;
    groupId?: bigint;
    isEdited: boolean;
    editHistory: Array<PostEdit>;
    timestamp: Time;
}> {
    return {
        id: value.id,
        postType: from_candid_PostType_n45(_uploadFile, _downloadFile, value.postType),
        seriousLikeCount: value.seriousLikeCount,
        likeCount: value.likeCount,
        content: await from_candid_MediaContent_n47(_uploadFile, _downloadFile, value.content),
        author: value.author,
        groupId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.groupId)),
        isEdited: value.isEdited,
        editHistory: await from_candid_vec_n50(_uploadFile, _downloadFile, value.editHistory),
        timestamp: value.timestamp
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: [] | [_ExternalBlob];
    text: [] | [string];
    image: [] | [_ExternalBlob];
}): Promise<{
    video?: ExternalBlob;
    text?: string;
    image?: ExternalBlob;
}> {
    return {
        video: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.video)),
        text: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.text)),
        image: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: _MediaContent;
    timestamp: _Time;
}): Promise<{
    content: MediaContent;
    timestamp: Time;
}> {
    return {
        content: await from_candid_MediaContent_n47(_uploadFile, _downloadFile, value.content),
        timestamp: value.timestamp
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isModerated: boolean;
    upvotes: Array<Principal>;
    content: string;
    parentCommentId: [] | [bigint];
    authorId: Principal;
    moderationReason: [] | [string];
    timestamp: bigint;
    sessionId: bigint;
}): {
    id: bigint;
    isModerated: boolean;
    upvotes: Array<Principal>;
    content: string;
    parentCommentId?: bigint;
    authorId: Principal;
    moderationReason?: string;
    timestamp: bigint;
    sessionId: bigint;
} {
    return {
        id: value.id,
        isModerated: value.isModerated,
        upvotes: value.upvotes,
        content: value.content,
        parentCommentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.parentCommentId)),
        authorId: value.authorId,
        moderationReason: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.moderationReason)),
        timestamp: value.timestamp,
        sessionId: value.sessionId
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    authorId: Principal;
    reactionType: _LiveReactionType;
    timestamp: bigint;
    sessionId: bigint;
}): {
    authorId: Principal;
    reactionType: LiveReactionType;
    timestamp: bigint;
    sessionId: bigint;
} {
    return {
        authorId: value.authorId,
        reactionType: from_candid_LiveReactionType_n59(_uploadFile, _downloadFile, value.reactionType),
        timestamp: value.timestamp,
        sessionId: value.sessionId
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    live: null;
} | {
    ended: null;
}): LiveSessionStatus {
    return "scheduled" in value ? LiveSessionStatus.scheduled : "live" in value ? LiveSessionStatus.live : "ended" in value ? LiveSessionStatus.ended : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    regular: null;
} | {
    newsFeed: null;
}): PostType {
    return "regular" in value ? PostType.regular : "newsFeed" in value ? PostType.newsFeed : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heart: null;
} | {
    clap: null;
} | {
    fire: null;
} | {
    wave: null;
}): LiveReactionType {
    return "heart" in value ? LiveReactionType.heart : "clap" in value ? LiveReactionType.clap : "fire" in value ? LiveReactionType.fire : "wave" in value ? LiveReactionType.wave : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveSession>): Array<LiveSession> {
    return value.map((x)=>from_candid_LiveSession_n22(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostEdit>): Promise<Array<PostEdit>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PostEdit_n51(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveComment>): Array<LiveComment> {
    return value.map((x)=>from_candid_LiveComment_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveReaction>): Array<LiveReaction> {
    return value.map((x)=>from_candid_LiveReaction_n57(_uploadFile, _downloadFile, x));
}
async function to_candid_CreateGroupArgs_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGroupArgs): Promise<_CreateGroupArgs> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LiveReactionType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LiveReactionType): _LiveReactionType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
async function to_candid_MediaContent_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaContent): Promise<_MediaContent> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PostType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): _PostType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: Principal;
    adminIds: Array<Principal>;
    name: string;
    createdAt: Time;
    description: string;
    coverImage?: ExternalBlob;
}): Promise<{
    creator: Principal;
    adminIds: Array<Principal>;
    name: string;
    createdAt: _Time;
    description: string;
    coverImage: [] | [_ExternalBlob];
}> {
    return {
        creator: value.creator,
        adminIds: value.adminIds,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        coverImage: value.coverImage ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.coverImage)) : candid_none()
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video?: ExternalBlob;
    text?: string;
    image?: ExternalBlob;
}): Promise<{
    video: [] | [_ExternalBlob];
    text: [] | [string];
    image: [] | [_ExternalBlob];
}> {
    return {
        video: value.video ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.video)) : candid_none(),
        text: value.text ? candid_some(value.text) : candid_none(),
        image: value.image ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    name: string;
    profilePhoto?: ExternalBlob;
    badges: Array<string>;
    civicTokenBalance: bigint;
    verifiedStatus: boolean;
    followerCount: bigint;
    location: string;
}): Promise<{
    bio: string;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    badges: Array<string>;
    civicTokenBalance: bigint;
    verifiedStatus: boolean;
    followerCount: bigint;
    location: string;
}> {
    return {
        bio: value.bio,
        name: value.name,
        profilePhoto: value.profilePhoto ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.profilePhoto)) : candid_none(),
        badges: value.badges,
        civicTokenBalance: value.civicTokenBalance,
        verifiedStatus: value.verifiedStatus,
        followerCount: value.followerCount,
        location: value.location
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LiveReactionType): {
    heart: null;
} | {
    clap: null;
} | {
    fire: null;
} | {
    wave: null;
} {
    return value == LiveReactionType.heart ? {
        heart: null
    } : value == LiveReactionType.clap ? {
        clap: null
    } : value == LiveReactionType.fire ? {
        fire: null
    } : value == LiveReactionType.wave ? {
        wave: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): {
    regular: null;
} | {
    newsFeed: null;
} {
    return value == PostType.regular ? {
        regular: null
    } : value == PostType.newsFeed ? {
        newsFeed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
